import { config } from "dotenv";
config({ path: ".env.local" });
import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import * as schema from "../lib/schema";

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle({ client: sql, schema });

interface VehicleSeed {
  vehicle: typeof schema.vehicles.$inferInsert;
  price: Omit<typeof schema.pricing.$inferInsert, "vehicleId">;
}

function rand(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

const SEED_DATA: VehicleSeed[] = [
  // ── Compact SUVs / Crossovers ─────────────────────────────────────
  {
    vehicle: {
      make: "Toyota",
      model: "RAV4",
      variant: "XLE AWD",
      year: 2024,
      bodyType: "SUV",
      fuelType: "Gas",
      transmission: "Automatic",
      drivetrain: "AWD",
      engineSpec: "2.5L 4-Cylinder Dynamic Force",
      horsepower: 203,
      torqueLbFt: 184,
      fuelEconomy: "7.6",
      seating: 5,
      safetyRating: "IIHS Top Safety Pick+",
      airbags: 8,
      features: ["heated_seats", "heated_steering_wheel", "awd", "apple_carplay", "android_auto", "remote_start", "toyota_safety_sense_3", "blind_spot_monitor", "rear_cross_traffic_alert", "adaptive_cruise_control"],
      colors: ["Lunar Rock", "Blueprint", "Midnight Black", "Ice Cap", "Ruby Flare Pearl", "Silver Sky"],
      description: "The Toyota RAV4 XLE AWD is Canada's best-selling SUV for good reason. With standard AWD, Toyota Safety Sense 3.0, heated seats and steering wheel, it's built for Canadian winters. The 2.5L Dynamic Force engine delivers 203 hp with excellent 7.6 L/100km fuel economy — saving you at the pump while tackling snow-covered roads with confidence.",
      cargoSpaceL: 1065,
      winterReady: true,
    },
    price: {
      msrp: "38550",
      dealerCost: "33800",
      marginFloorPct: "0.06",
      competitorPrice: "44800",
      competitorName: "Honda CR-V Touring AWD",
      inventoryAgeDays: rand(10, 45),
      stockQuantity: rand(3, 8),
      maxDiscountPct: "0.08",
      destinationFee: "1950",
      accessoriesCost: "400",
      accessoriesValue: "1200",
      warrantyExtCost: "800",
      warrantyExtValue: "2500",
      financingRatePct: "4.99",
      cashbackOffer: "500",
    },
  },
  {
    vehicle: {
      make: "Honda",
      model: "CR-V",
      variant: "Touring AWD",
      year: 2024,
      bodyType: "SUV",
      fuelType: "Gas",
      transmission: "CVT",
      drivetrain: "AWD",
      engineSpec: "1.5L Turbocharged 4-Cylinder",
      horsepower: 190,
      torqueLbFt: 179,
      fuelEconomy: "8.1",
      seating: 5,
      safetyRating: "IIHS Top Safety Pick+",
      airbags: 10,
      features: ["heated_seats", "ventilated_seats", "heated_steering_wheel", "awd", "apple_carplay", "android_auto", "wireless_charging", "panoramic_sunroof", "honda_sensing", "remote_start", "power_liftgate", "leather_seats"],
      colors: ["Platinum White", "Crystal Black", "Canyon River Blue", "Radiant Red", "Urban Gray", "Meteoroid Gray"],
      description: "The Honda CR-V Touring is the premium choice in Canada's compact SUV segment. Loaded with ventilated leather seats, panoramic sunroof, wireless charging, and the full Honda Sensing suite, it's a luxury-feel SUV at a mainstream price. AWD is standard, and the 1.5T engine provides smooth, responsive power for highway merging and mountain passes alike.",
      cargoSpaceL: 1110,
      winterReady: true,
    },
    price: {
      msrp: "44800",
      dealerCost: "39400",
      marginFloorPct: "0.06",
      competitorPrice: "38550",
      competitorName: "Toyota RAV4 XLE AWD",
      inventoryAgeDays: rand(10, 50),
      stockQuantity: rand(2, 6),
      maxDiscountPct: "0.07",
      destinationFee: "1990",
      accessoriesCost: "450",
      accessoriesValue: "1300",
      warrantyExtCost: "850",
      warrantyExtValue: "2600",
      financingRatePct: "3.99",
      cashbackOffer: null,
    },
  },
  {
    vehicle: {
      make: "Hyundai",
      model: "Tucson",
      variant: "Ultimate AWD",
      year: 2024,
      bodyType: "SUV",
      fuelType: "Gas",
      transmission: "Automatic",
      drivetrain: "AWD",
      engineSpec: "2.5L 4-Cylinder Smartstream",
      horsepower: 187,
      torqueLbFt: 178,
      fuelEconomy: "8.2",
      seating: 5,
      safetyRating: "IIHS Top Safety Pick+",
      airbags: 6,
      features: ["heated_seats", "ventilated_seats", "heated_steering_wheel", "awd", "apple_carplay", "android_auto", "panoramic_sunroof", "hyundai_smartsense", "remote_start", "surround_view_monitor", "heads_up_display", "bose_audio"],
      colors: ["Amazon Grey", "Phantom Black", "Shimmering Silver", "Calypso Red", "Twilight Black", "Nocturne Grey"],
      description: "The Hyundai Tucson Ultimate AWD packs segment-leading tech into a bold, modern design. With a panoramic sunroof, heads-up display, surround-view camera, and Bose premium audio, it feels like a luxury SUV at half the price. Hyundai's comprehensive 5-year/100,000 km warranty is among the best in Canada — peace of mind for years of harsh winters.",
      cargoSpaceL: 1095,
      winterReady: true,
    },
    price: {
      msrp: "43999",
      dealerCost: "38700",
      marginFloorPct: "0.06",
      competitorPrice: "41495",
      competitorName: "Kia Sportage X-Line AWD",
      inventoryAgeDays: rand(5, 60),
      stockQuantity: rand(2, 7),
      maxDiscountPct: "0.09",
      destinationFee: "1950",
      accessoriesCost: "380",
      accessoriesValue: "1150",
      warrantyExtCost: "750",
      warrantyExtValue: "2400",
      financingRatePct: "3.49",
      cashbackOffer: "750",
    },
  },
  {
    vehicle: {
      make: "Kia",
      model: "Sportage",
      variant: "X-Line AWD",
      year: 2024,
      bodyType: "SUV",
      fuelType: "Gas",
      transmission: "Automatic",
      drivetrain: "AWD",
      engineSpec: "2.5L 4-Cylinder Smartstream",
      horsepower: 187,
      torqueLbFt: 178,
      fuelEconomy: "8.0",
      seating: 5,
      safetyRating: "IIHS Top Safety Pick+",
      airbags: 6,
      features: ["heated_seats", "heated_steering_wheel", "awd", "apple_carplay", "android_auto", "panoramic_curved_display", "remote_start", "dual_zone_climate", "smart_power_liftgate", "drive_modes"],
      colors: ["Dawning Red", "Snow White Pearl", "Gravity Grey", "Runway Red", "Sparkling Silver", "Yacht Blue"],
      description: "The Kia Sportage X-Line AWD turns heads with its rugged styling and panoramic curved dual-display interior. It offers exceptional value with standard AWD, heated seats, and Kia's confident 5-year/100,000 km warranty. Smart enough for city commutes and tough enough for cottage country weekends, it's a versatile choice for Canadian families.",
      cargoSpaceL: 1089,
      winterReady: true,
    },
    price: {
      msrp: "41495",
      dealerCost: "36500",
      marginFloorPct: "0.06",
      competitorPrice: "43999",
      competitorName: "Hyundai Tucson Ultimate AWD",
      inventoryAgeDays: rand(10, 55),
      stockQuantity: rand(2, 6),
      maxDiscountPct: "0.08",
      destinationFee: "1950",
      accessoriesCost: "380",
      accessoriesValue: "1100",
      warrantyExtCost: "750",
      warrantyExtValue: "2400",
      financingRatePct: "4.49",
      cashbackOffer: "500",
    },
  },
  {
    vehicle: {
      make: "Mazda",
      model: "CX-50",
      variant: "GT Turbo AWD",
      year: 2024,
      bodyType: "SUV",
      fuelType: "Gas",
      transmission: "Automatic",
      drivetrain: "AWD",
      engineSpec: "2.5L Turbocharged 4-Cylinder Skyactiv-G",
      horsepower: 256,
      torqueLbFt: 320,
      fuelEconomy: "9.5",
      seating: 5,
      safetyRating: "IIHS Top Safety Pick+",
      airbags: 10,
      features: ["heated_seats", "ventilated_seats", "heated_steering_wheel", "awd", "apple_carplay", "android_auto", "turbo_engine", "off_road_mode", "bose_audio", "heads_up_display", "panoramic_sunroof", "leather_seats"],
      colors: ["Zircon Sand", "Soul Red Crystal", "Machine Grey", "Jet Black", "Rhodium White", "Polymetal Grey"],
      description: "The Mazda CX-50 GT Turbo AWD is the enthusiast's SUV — 256 turbocharged horsepower, premium Nappa leather, Bose audio, and Mazda's signature driving dynamics. Its rugged outdoor styling with off-road mode makes it equally at home on Trans-Canada Highway road trips and Muskoka back roads. For Canadians who want an SUV that's actually fun to drive.",
      cargoSpaceL: 1031,
      winterReady: true,
    },
    price: {
      msrp: "45950",
      dealerCost: "40600",
      marginFloorPct: "0.06",
      competitorPrice: "44800",
      competitorName: "Honda CR-V Touring AWD",
      inventoryAgeDays: rand(15, 70),
      stockQuantity: rand(1, 5),
      maxDiscountPct: "0.07",
      destinationFee: "2050",
      accessoriesCost: "420",
      accessoriesValue: "1250",
      warrantyExtCost: "850",
      warrantyExtValue: "2500",
      financingRatePct: "4.50",
      cashbackOffer: null,
    },
  },
  {
    vehicle: {
      make: "Subaru",
      model: "Forester",
      variant: "Premier",
      year: 2025,
      bodyType: "SUV",
      fuelType: "Gas",
      transmission: "CVT",
      drivetrain: "AWD",
      engineSpec: "2.5L Horizontally-Opposed 4-Cylinder Boxer",
      horsepower: 182,
      torqueLbFt: 176,
      fuelEconomy: "8.0",
      seating: 5,
      safetyRating: "IIHS Top Safety Pick+",
      airbags: 8,
      features: ["heated_seats", "heated_steering_wheel", "symmetrical_awd", "apple_carplay", "android_auto", "eyesight_driver_assist", "x_mode", "remote_start", "panoramic_sunroof", "leather_seats", "power_liftgate"],
      colors: ["Cascade Green", "Crystal White Pearl", "Magnetite Grey", "Crimson Red", "Ice Silver", "Horizon Blue"],
      description: "The Subaru Forester Premier is the go-to choice for Canadian outdoor enthusiasts. Subaru's legendary Symmetrical AWD and X-Mode make it unstoppable in snow, mud, and gravel. With EyeSight driver assist, a panoramic sunroof, and class-leading visibility, it's the SUV that gets you to the ski hill, the lake, and back home safely — no matter the weather.",
      cargoSpaceL: 1095,
      winterReady: true,
    },
    price: {
      msrp: "41495",
      dealerCost: "36900",
      marginFloorPct: "0.06",
      competitorPrice: "38550",
      competitorName: "Toyota RAV4 XLE AWD",
      inventoryAgeDays: rand(10, 50),
      stockQuantity: rand(2, 5),
      maxDiscountPct: "0.07",
      destinationFee: "1900",
      accessoriesCost: "400",
      accessoriesValue: "1200",
      warrantyExtCost: "800",
      warrantyExtValue: "2400",
      financingRatePct: "4.99",
      cashbackOffer: null,
    },
  },
  {
    vehicle: {
      make: "Ford",
      model: "Escape",
      variant: "ST-Line AWD",
      year: 2024,
      bodyType: "SUV",
      fuelType: "Gas",
      transmission: "Automatic",
      drivetrain: "AWD",
      engineSpec: "1.5L EcoBoost Turbocharged 3-Cylinder",
      horsepower: 180,
      torqueLbFt: 190,
      fuelEconomy: "8.4",
      seating: 5,
      safetyRating: "5-Star NHTSA",
      airbags: 8,
      features: ["heated_seats", "heated_steering_wheel", "awd", "apple_carplay", "android_auto", "ford_copilot360", "remote_start", "sport_tuned_suspension", "b_o_audio", "wireless_charging"],
      colors: ["Vapor Blue", "Star White", "Agate Black", "Rapid Red", "Iconic Silver", "Carbonized Grey"],
      description: "The Ford Escape ST-Line AWD brings a sporty edge to the compact SUV segment. With sport-tuned suspension, unique ST-Line styling, and Ford Co-Pilot360 safety tech, it's designed for Canadians who want more driver engagement. The efficient EcoBoost engine keeps fuel costs down during long Canadian commutes while AWD handles everything winter throws at you.",
      cargoSpaceL: 1030,
      winterReady: true,
    },
    price: {
      msrp: "42999",
      dealerCost: "37800",
      marginFloorPct: "0.06",
      competitorPrice: "38550",
      competitorName: "Toyota RAV4 XLE AWD",
      inventoryAgeDays: rand(20, 80),
      stockQuantity: rand(2, 7),
      maxDiscountPct: "0.10",
      destinationFee: "2000",
      accessoriesCost: "420",
      accessoriesValue: "1200",
      warrantyExtCost: "800",
      warrantyExtValue: "2500",
      financingRatePct: "2.99",
      cashbackOffer: "1000",
    },
  },

  // ── Mid-Size SUVs ─────────────────────────────────────────────────
  {
    vehicle: {
      make: "Toyota",
      model: "Highlander",
      variant: "XLE AWD",
      year: 2024,
      bodyType: "SUV",
      fuelType: "Gas",
      transmission: "Automatic",
      drivetrain: "AWD",
      engineSpec: "2.4L Turbocharged 4-Cylinder",
      horsepower: 265,
      torqueLbFt: 310,
      fuelEconomy: "8.9",
      seating: 8,
      safetyRating: "IIHS Top Safety Pick+",
      airbags: 8,
      features: ["heated_seats", "heated_steering_wheel", "awd", "apple_carplay", "android_auto", "toyota_safety_sense_3", "remote_start", "third_row_seating", "power_liftgate", "tri_zone_climate"],
      colors: ["Celestial Silver", "Midnight Black", "Blueprint", "Wind Chill Pearl", "Ruby Flare Pearl", "Cypress Green"],
      description: "The Toyota Highlander XLE AWD is the ultimate Canadian family hauler. With 8 seats, a powerful 2.4T engine, and Toyota's bulletproof reliability, it handles hockey practice runs, Costco trips, and family road trips to the Maritimes with ease. Standard AWD and Toyota Safety Sense 3.0 keep everyone safe through blizzards and beyond.",
      cargoSpaceL: 1150,
      winterReady: true,
    },
    price: {
      msrp: "50550",
      dealerCost: "44500",
      marginFloorPct: "0.06",
      competitorPrice: "54999",
      competitorName: "Hyundai Palisade Urban AWD",
      inventoryAgeDays: rand(10, 40),
      stockQuantity: rand(1, 5),
      maxDiscountPct: "0.07",
      destinationFee: "2050",
      accessoriesCost: "500",
      accessoriesValue: "1400",
      warrantyExtCost: "900",
      warrantyExtValue: "2800",
      financingRatePct: "5.49",
      cashbackOffer: null,
    },
  },
  {
    vehicle: {
      make: "Hyundai",
      model: "Palisade",
      variant: "Urban AWD",
      year: 2024,
      bodyType: "SUV",
      fuelType: "Gas",
      transmission: "Automatic",
      drivetrain: "AWD",
      engineSpec: "3.8L V6",
      horsepower: 291,
      torqueLbFt: 262,
      fuelEconomy: "10.7",
      seating: 8,
      safetyRating: "IIHS Top Safety Pick+",
      airbags: 8,
      features: ["heated_seats", "ventilated_seats", "heated_steering_wheel", "awd", "apple_carplay", "android_auto", "remote_start", "third_row_seating", "nappa_leather", "surround_view_monitor", "heads_up_display", "harman_kardon_audio", "power_folding_third_row"],
      colors: ["Hyper White", "Abyss Black", "Graphite Metallic", "Sierra Burgundy", "Steel Graphite", "Moonlight Cloud"],
      description: "The Hyundai Palisade Urban AWD brings genuine luxury to the 3-row SUV segment at a fraction of the cost of premium brands. With Nappa leather, Harman Kardon audio, a heads-up display, and seating for 8, it rivals vehicles costing $20K more. For large Canadian families, it's the smart choice — premium comfort with Hyundai's class-leading 5-year warranty.",
      cargoSpaceL: 1297,
      winterReady: true,
    },
    price: {
      msrp: "54999",
      dealerCost: "48400",
      marginFloorPct: "0.06",
      competitorPrice: "54995",
      competitorName: "Kia Telluride SX AWD",
      inventoryAgeDays: rand(5, 35),
      stockQuantity: rand(1, 4),
      maxDiscountPct: "0.06",
      destinationFee: "2050",
      accessoriesCost: "500",
      accessoriesValue: "1400",
      warrantyExtCost: "850",
      warrantyExtValue: "2600",
      financingRatePct: "4.49",
      cashbackOffer: null,
    },
  },
  {
    vehicle: {
      make: "Kia",
      model: "Telluride",
      variant: "SX AWD",
      year: 2024,
      bodyType: "SUV",
      fuelType: "Gas",
      transmission: "Automatic",
      drivetrain: "AWD",
      engineSpec: "3.8L V6",
      horsepower: 291,
      torqueLbFt: 262,
      fuelEconomy: "10.8",
      seating: 8,
      safetyRating: "IIHS Top Safety Pick+",
      airbags: 8,
      features: ["heated_seats", "ventilated_seats", "heated_steering_wheel", "awd", "apple_carplay", "android_auto", "remote_start", "third_row_seating", "nappa_leather", "surround_view_monitor", "heads_up_display", "harman_kardon_audio", "tow_package"],
      colors: ["Glacial White Pearl", "Ebony Black", "Gravity Grey", "Sangria Red", "Jungle Wood Green", "Dawning Red"],
      description: "The Kia Telluride SX AWD is an award-winning 3-row SUV that has consistently won 'Best in Class' honors. Nappa leather, Harman Kardon audio, and a commanding road presence make it feel like a $70K luxury SUV. With 8 seats, a 5,000 lb tow rating, and Kia's comprehensive warranty, it's perfect for Canadian families who need space, capability, and style.",
      cargoSpaceL: 1304,
      winterReady: true,
    },
    price: {
      msrp: "54995",
      dealerCost: "48200",
      marginFloorPct: "0.06",
      competitorPrice: "54999",
      competitorName: "Hyundai Palisade Urban AWD",
      inventoryAgeDays: rand(5, 30),
      stockQuantity: rand(1, 4),
      maxDiscountPct: "0.06",
      destinationFee: "2050",
      accessoriesCost: "500",
      accessoriesValue: "1400",
      warrantyExtCost: "850",
      warrantyExtValue: "2600",
      financingRatePct: "4.49",
      cashbackOffer: null,
    },
  },

  // ── Trucks ────────────────────────────────────────────────────────
  {
    vehicle: {
      make: "Ford",
      model: "F-150",
      variant: "XLT 4x4 SuperCrew",
      year: 2024,
      bodyType: "Truck",
      fuelType: "Gas",
      transmission: "Automatic",
      drivetrain: "4WD",
      engineSpec: "5.0L V8 Ti-VCT",
      horsepower: 400,
      torqueLbFt: 410,
      fuelEconomy: "11.9",
      seating: 6,
      safetyRating: "5-Star NHTSA",
      airbags: 8,
      features: ["heated_seats", "4wd", "apple_carplay", "android_auto", "ford_copilot360", "remote_start", "pro_power_onboard", "trailer_tow_package", "spray_in_bedliner", "tailgate_step"],
      colors: ["Iconic Silver", "Oxford White", "Agate Black", "Rapid Red", "Area 51", "Carbonized Grey"],
      description: "The Ford F-150 XLT is Canada's best-selling vehicle — period. The 5.0L V8 delivers 400 hp and 410 lb-ft for towing boats, trailers, and snowmobiles. Pro Power Onboard turns it into a mobile generator for tailgating or job sites. With 4x4, it's the workhorse that millions of Canadians rely on from coast to coast.",
      cargoSpaceL: null,
      winterReady: true,
    },
    price: {
      msrp: "56475",
      dealerCost: "49700",
      marginFloorPct: "0.06",
      competitorPrice: "55780",
      competitorName: "RAM 1500 Big Horn 4x4",
      inventoryAgeDays: rand(10, 50),
      stockQuantity: rand(2, 6),
      maxDiscountPct: "0.10",
      destinationFee: "2200",
      accessoriesCost: "600",
      accessoriesValue: "1800",
      warrantyExtCost: "950",
      warrantyExtValue: "3000",
      financingRatePct: "3.99",
      cashbackOffer: "2000",
    },
  },
  {
    vehicle: {
      make: "Toyota",
      model: "Tacoma",
      variant: "TRD Sport 4x4",
      year: 2024,
      bodyType: "Truck",
      fuelType: "Gas",
      transmission: "Automatic",
      drivetrain: "4WD",
      engineSpec: "2.4L Turbocharged 4-Cylinder i-FORCE",
      horsepower: 278,
      torqueLbFt: 317,
      fuelEconomy: "10.2",
      seating: 5,
      safetyRating: "5-Star NHTSA",
      airbags: 8,
      features: ["heated_seats", "4wd", "apple_carplay", "android_auto", "toyota_safety_sense_3", "remote_start", "multi_terrain_select", "crawl_control", "sport_tuned_suspension"],
      colors: ["Ice Cap", "Underground", "Celestial Silver", "Supersonic Red", "Midnight Black", "Bronze Oxide"],
      description: "The all-new Toyota Tacoma TRD Sport is the mid-size truck for Canadians who work hard and play harder. The new 2.4T i-FORCE engine provides serious capability while the multi-terrain select system conquers any trail. Toyota's legendary reliability means it'll still be running strong through decade after decade of Canadian winters.",
      cargoSpaceL: null,
      winterReady: true,
    },
    price: {
      msrp: "48450",
      dealerCost: "42700",
      marginFloorPct: "0.06",
      competitorPrice: "56475",
      competitorName: "Ford F-150 XLT 4x4",
      inventoryAgeDays: rand(5, 35),
      stockQuantity: rand(1, 4),
      maxDiscountPct: "0.06",
      destinationFee: "2050",
      accessoriesCost: "500",
      accessoriesValue: "1500",
      warrantyExtCost: "850",
      warrantyExtValue: "2600",
      financingRatePct: "5.49",
      cashbackOffer: null,
    },
  },
  {
    vehicle: {
      make: "RAM",
      model: "1500",
      variant: "Big Horn 4x4",
      year: 2024,
      bodyType: "Truck",
      fuelType: "Gas",
      transmission: "Automatic",
      drivetrain: "4WD",
      engineSpec: "5.7L HEMI V8 eTorque",
      horsepower: 395,
      torqueLbFt: 410,
      fuelEconomy: "11.3",
      seating: 6,
      safetyRating: "5-Star NHTSA",
      airbags: 8,
      features: ["heated_seats", "heated_steering_wheel", "4wd", "apple_carplay", "android_auto", "remote_start", "12_inch_uconnect_screen", "trailer_tow_package", "class_exclusive_coil_spring_rear", "etorque_mild_hybrid"],
      colors: ["Patriot Blue", "Bright White", "Diamond Black", "Flame Red", "Billet Silver", "Granite Crystal"],
      description: "The RAM 1500 Big Horn offers the most refined ride in the full-size truck segment thanks to its class-exclusive coil-spring rear suspension. The 5.7L HEMI V8 with eTorque mild hybrid delivers 395 hp with improved fuel efficiency. The massive 12-inch Uconnect touchscreen and premium interior make long Canadian highway hauls comfortable.",
      cargoSpaceL: null,
      winterReady: true,
    },
    price: {
      msrp: "55780",
      dealerCost: "48600",
      marginFloorPct: "0.06",
      competitorPrice: "56475",
      competitorName: "Ford F-150 XLT 4x4",
      inventoryAgeDays: rand(15, 70),
      stockQuantity: rand(2, 6),
      maxDiscountPct: "0.10",
      destinationFee: "2200",
      accessoriesCost: "550",
      accessoriesValue: "1700",
      warrantyExtCost: "900",
      warrantyExtValue: "2800",
      financingRatePct: "3.49",
      cashbackOffer: "1500",
    },
  },

  // ── Sedans ────────────────────────────────────────────────────────
  {
    vehicle: {
      make: "Honda",
      model: "Civic",
      variant: "Touring",
      year: 2024,
      bodyType: "Sedan",
      fuelType: "Gas",
      transmission: "CVT",
      drivetrain: "FWD",
      engineSpec: "1.5L Turbocharged 4-Cylinder",
      horsepower: 180,
      torqueLbFt: 177,
      fuelEconomy: "6.8",
      seating: 5,
      safetyRating: "IIHS Top Safety Pick+",
      airbags: 10,
      features: ["heated_seats", "apple_carplay", "android_auto", "wireless_charging", "honda_sensing", "remote_start", "bose_audio", "leather_seats", "sunroof", "wireless_carplay"],
      colors: ["Platinum White", "Crystal Black", "Rallye Red", "Sonic Grey", "Aegean Blue", "Meteoroid Grey"],
      description: "The Honda Civic Touring is Canada's best-selling car for over two decades, and the latest generation shows why. Exceptional 6.8 L/100km fuel economy saves hundreds annually at Canadian gas prices. Bose audio, wireless CarPlay, and Honda Sensing make every commute premium. It's the smart choice for city drivers and young professionals across Canada.",
      cargoSpaceL: 410,
      winterReady: false,
    },
    price: {
      msrp: "35350",
      dealerCost: "31200",
      marginFloorPct: "0.06",
      competitorPrice: "39990",
      competitorName: "Toyota Camry XSE AWD",
      inventoryAgeDays: rand(5, 40),
      stockQuantity: rand(3, 8),
      maxDiscountPct: "0.06",
      destinationFee: "1850",
      accessoriesCost: "350",
      accessoriesValue: "1000",
      warrantyExtCost: "700",
      warrantyExtValue: "2200",
      financingRatePct: "4.99",
      cashbackOffer: null,
    },
  },
  {
    vehicle: {
      make: "Toyota",
      model: "Camry",
      variant: "XSE AWD",
      year: 2025,
      bodyType: "Sedan",
      fuelType: "Gas",
      transmission: "Automatic",
      drivetrain: "AWD",
      engineSpec: "2.5L 4-Cylinder Dynamic Force",
      horsepower: 203,
      torqueLbFt: 184,
      fuelEconomy: "7.8",
      seating: 5,
      safetyRating: "IIHS Top Safety Pick+",
      airbags: 10,
      features: ["heated_seats", "heated_steering_wheel", "awd", "apple_carplay", "android_auto", "toyota_safety_sense_3", "remote_start", "sport_tuned_suspension", "jbl_audio", "panoramic_roof"],
      colors: ["Supersonic Red", "Ice Cap", "Midnight Black", "Underground", "Celestial Silver", "Wind Chill Pearl"],
      description: "The Toyota Camry XSE AWD is the rare sedan that offers all-wheel drive — a huge advantage for Canadian winters. With sport-tuned suspension, JBL premium audio, and aggressive XSE styling, it's for drivers who want sedan efficiency with SUV-level winter traction. At 7.8 L/100km with AWD, it's remarkably fuel-efficient for a winter-capable car.",
      cargoSpaceL: 427,
      winterReady: true,
    },
    price: {
      msrp: "39990",
      dealerCost: "35200",
      marginFloorPct: "0.06",
      competitorPrice: "41499",
      competitorName: "Hyundai Sonata Ultimate",
      inventoryAgeDays: rand(10, 45),
      stockQuantity: rand(2, 6),
      maxDiscountPct: "0.07",
      destinationFee: "1900",
      accessoriesCost: "380",
      accessoriesValue: "1100",
      warrantyExtCost: "750",
      warrantyExtValue: "2300",
      financingRatePct: "4.49",
      cashbackOffer: "500",
    },
  },
  {
    vehicle: {
      make: "Hyundai",
      model: "Sonata",
      variant: "Ultimate",
      year: 2024,
      bodyType: "Sedan",
      fuelType: "Gas",
      transmission: "Automatic",
      drivetrain: "FWD",
      engineSpec: "2.5L 4-Cylinder Smartstream",
      horsepower: 191,
      torqueLbFt: 181,
      fuelEconomy: "7.3",
      seating: 5,
      safetyRating: "IIHS Top Safety Pick+",
      airbags: 10,
      features: ["heated_seats", "ventilated_seats", "heated_steering_wheel", "apple_carplay", "android_auto", "panoramic_sunroof", "highway_driving_assist_2", "remote_start", "bose_audio", "surround_view_monitor", "heads_up_display"],
      colors: ["Shimmering Silver", "Phantom Black", "Hampton Grey", "Nocturne Grey", "Quartz White", "Flame Red"],
      description: "The Hyundai Sonata Ultimate packs near-luxury features into a mid-size sedan at an incredible value. Highway Driving Assist 2 provides semi-autonomous driving on Canadian highways, while the panoramic sunroof and Bose audio create a premium cabin experience. With excellent 7.3 L/100km fuel economy and Hyundai's 5-year warranty, it's a smart, comfortable choice.",
      cargoSpaceL: 453,
      winterReady: false,
    },
    price: {
      msrp: "41499",
      dealerCost: "36500",
      marginFloorPct: "0.06",
      competitorPrice: "39990",
      competitorName: "Toyota Camry XSE AWD",
      inventoryAgeDays: rand(20, 75),
      stockQuantity: rand(2, 5),
      maxDiscountPct: "0.09",
      destinationFee: "1900",
      accessoriesCost: "370",
      accessoriesValue: "1100",
      warrantyExtCost: "750",
      warrantyExtValue: "2400",
      financingRatePct: "3.49",
      cashbackOffer: "1000",
    },
  },

  // ── Electric ──────────────────────────────────────────────────────
  {
    vehicle: {
      make: "Tesla",
      model: "Model Y",
      variant: "Long Range AWD",
      year: 2024,
      bodyType: "SUV",
      fuelType: "Electric",
      transmission: "Single-Speed",
      drivetrain: "AWD",
      engineSpec: "Dual Motor Electric AWD",
      horsepower: 384,
      torqueLbFt: 375,
      fuelEconomy: "16.0",
      seating: 5,
      safetyRating: "5-Star NHTSA",
      airbags: 8,
      features: ["heated_seats", "heated_steering_wheel", "awd", "autopilot", "over_the_air_updates", "15_inch_touchscreen", "glass_roof", "sentry_mode", "supercharger_network", "531km_range"],
      colors: ["Pearl White", "Solid Black", "Midnight Silver", "Deep Blue", "Red Multi-Coat", "Quicksilver"],
      description: "The Tesla Model Y Long Range AWD offers 531 km of range — enough to drive Toronto to Montreal on a single charge. Dual motor AWD provides instant torque in any weather, while Tesla's Supercharger network across Canada means road trips are hassle-free. Eligible for the federal $5,000 iZEV rebate and provincial rebates in QC and BC.",
      cargoSpaceL: 2158,
      winterReady: true,
    },
    price: {
      msrp: "59990",
      dealerCost: "55800",
      marginFloorPct: "0.04",
      competitorPrice: "54999",
      competitorName: "Hyundai IONIQ 5 Preferred AWD LR",
      inventoryAgeDays: rand(5, 25),
      stockQuantity: rand(1, 4),
      maxDiscountPct: "0.03",
      destinationFee: "1600",
      accessoriesCost: "300",
      accessoriesValue: "900",
      warrantyExtCost: "1200",
      warrantyExtValue: "3500",
      financingRatePct: null,
      cashbackOffer: null,
    },
  },
  {
    vehicle: {
      make: "Hyundai",
      model: "IONIQ 5",
      variant: "Preferred AWD Long Range",
      year: 2024,
      bodyType: "SUV",
      fuelType: "Electric",
      transmission: "Single-Speed",
      drivetrain: "AWD",
      engineSpec: "Dual Motor Electric AWD 800V",
      horsepower: 320,
      torqueLbFt: 446,
      fuelEconomy: "18.1",
      seating: 5,
      safetyRating: "IIHS Top Safety Pick+",
      airbags: 6,
      features: ["heated_seats", "heated_steering_wheel", "awd", "800v_ultrafast_charging", "vehicle_to_load", "apple_carplay", "android_auto", "remote_start", "488km_range", "hyundai_smartsense"],
      colors: ["Lucid Blue", "Atlas White", "Digital Teal", "Cyber Grey", "Gravity Gold", "Abyss Black"],
      description: "The Hyundai IONIQ 5 is a game-changer with its 800V ultra-fast charging — add 350 km of range in just 18 minutes. With 488 km total range and dual motor AWD, it handles Canadian winters confidently. Vehicle-to-Load lets you power camping gear or even your home during outages. Eligible for the federal $5,000 iZEV rebate.",
      cargoSpaceL: 1587,
      winterReady: true,
    },
    price: {
      msrp: "54999",
      dealerCost: "49000",
      marginFloorPct: "0.05",
      competitorPrice: "59990",
      competitorName: "Tesla Model Y Long Range AWD",
      inventoryAgeDays: rand(10, 45),
      stockQuantity: rand(1, 4),
      maxDiscountPct: "0.06",
      destinationFee: "1950",
      accessoriesCost: "350",
      accessoriesValue: "1000",
      warrantyExtCost: "1000",
      warrantyExtValue: "3200",
      financingRatePct: "3.99",
      cashbackOffer: null,
    },
  },
  {
    vehicle: {
      make: "Chevrolet",
      model: "Equinox EV",
      variant: "2LT AWD",
      year: 2024,
      bodyType: "SUV",
      fuelType: "Electric",
      transmission: "Single-Speed",
      drivetrain: "AWD",
      engineSpec: "Dual Motor Electric AWD Ultium",
      horsepower: 290,
      torqueLbFt: 346,
      fuelEconomy: "17.5",
      seating: 5,
      safetyRating: "5-Star NHTSA",
      airbags: 8,
      features: ["heated_seats", "heated_steering_wheel", "awd", "apple_carplay", "android_auto", "super_cruise_capable", "17_inch_touchscreen", "remote_start", "459km_range", "one_pedal_driving"],
      colors: ["Summit White", "Black", "Riptide Blue", "Radiant Red", "Sterling Grey", "Lakeshore Blue"],
      description: "The Chevrolet Equinox EV 2LT makes electric driving accessible for everyday Canadians. At under $50K with 459 km of range and AWD, it's one of the most affordable electric SUVs in Canada. Super Cruise capability and a massive 17-inch touchscreen bring cutting-edge tech. Eligible for the federal $5,000 iZEV rebate, bringing the effective price even lower.",
      cargoSpaceL: 1614,
      winterReady: true,
    },
    price: {
      msrp: "49995",
      dealerCost: "44500",
      marginFloorPct: "0.05",
      competitorPrice: "54999",
      competitorName: "Hyundai IONIQ 5 Preferred AWD LR",
      inventoryAgeDays: rand(10, 50),
      stockQuantity: rand(2, 5),
      maxDiscountPct: "0.08",
      destinationFee: "2000",
      accessoriesCost: "350",
      accessoriesValue: "1000",
      warrantyExtCost: "1000",
      warrantyExtValue: "3200",
      financingRatePct: "2.99",
      cashbackOffer: "1500",
    },
  },

  // ── Hybrid ────────────────────────────────────────────────────────
  {
    vehicle: {
      make: "Toyota",
      model: "RAV4 Hybrid",
      variant: "XLE AWD",
      year: 2024,
      bodyType: "SUV",
      fuelType: "Hybrid",
      transmission: "eCVT",
      drivetrain: "AWD",
      engineSpec: "2.5L 4-Cylinder Hybrid Synergy Drive",
      horsepower: 219,
      torqueLbFt: 163,
      fuelEconomy: "5.8",
      seating: 5,
      safetyRating: "IIHS Top Safety Pick+",
      airbags: 8,
      features: ["heated_seats", "heated_steering_wheel", "electronic_awd", "apple_carplay", "android_auto", "toyota_safety_sense_3", "remote_start", "ev_mode", "regenerative_braking", "power_liftgate"],
      colors: ["Lunar Rock", "Blueprint", "Midnight Black", "Ice Cap", "Ruby Flare Pearl", "Silver Sky"],
      description: "The Toyota RAV4 Hybrid XLE AWD is the fuel economy champion — just 5.8 L/100km saves you over $1,000/year at the pump compared to gas SUVs. Electronic AWD provides seamless winter traction with zero driver input. It's the practical, eco-conscious choice for Canadian commuters who want SUV versatility without the fuel bills. No plugging in required.",
      cargoSpaceL: 1065,
      winterReady: true,
    },
    price: {
      msrp: "40550",
      dealerCost: "35700",
      marginFloorPct: "0.06",
      competitorPrice: "38550",
      competitorName: "Toyota RAV4 XLE AWD",
      inventoryAgeDays: rand(5, 30),
      stockQuantity: rand(1, 4),
      maxDiscountPct: "0.06",
      destinationFee: "1950",
      accessoriesCost: "400",
      accessoriesValue: "1200",
      warrantyExtCost: "850",
      warrantyExtValue: "2600",
      financingRatePct: "5.49",
      cashbackOffer: null,
    },
  },
];

async function main() {
  console.log("Seeding database with 20 Canadian market vehicles...\n");

  // Clear existing data
  await db.delete(schema.pricing);
  await db.delete(schema.offers);
  await db.delete(schema.conversations);
  await db.delete(schema.vehicles);
  console.log("Cleared existing data.");

  for (const { vehicle, price } of SEED_DATA) {
    const [inserted] = await db
      .insert(schema.vehicles)
      .values(vehicle)
      .returning({ id: schema.vehicles.id });

    await db.insert(schema.pricing).values({
      ...price,
      vehicleId: inserted.id,
    });

    console.log(`  ✓ ${vehicle.year} ${vehicle.make} ${vehicle.model} ${vehicle.variant} — $${Number(price.msrp).toLocaleString()}`);
  }

  console.log(`\nDone! Seeded ${SEED_DATA.length} vehicles with pricing data.`);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
